spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: email-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    topic:
      name: order-topics
  mail:
    host: smtp.gmail.com
    username: Spring Boot Email
    password: cmcszbyywicezgny
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'

server:
  error:
    include-message: always
  port: 8088