spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: email-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
    topic:
      name: order-topics
  mail:
    host: smtp.gmail.com
    username: dzakirinmd@gmail.com
    password: cmcs zbyy wice zgny
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
  datasource:
    url: 'jdbc:postgresql://localhost:55000/kafka_microservice'
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  error:
    include-message: always
  port: 8088